### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by lordcrekit** [lordcrekit/MI-449-SS17-740-html-semantic-elements-5BSgA-#1]
@chrisvfritz Can you take a look at this? It's [hosted here](https://lordcrekit.github.io/MI-449-SS17-740-html-semantic-elements-5BSgA-/) and meets the following criteria:

- [x] Place a `nav` element at the top of the page that includes (fake) links to other pages
- [x] Use the `main` element appropriately
- [x] Include three products your store sells, all listed on the same Products page
- [x] For each product, correctly use an `article`, `header`, and `footer` element and one or more `section` elements
- [x] Use `figure` and `figcaption` to show what each product looks like
- [x] Each product includes a `nav` element with one or more links to related products (the links don't have to go anywhere)
- [x] Use an `aside` in one or more products to advertise a promotion or discount for that product

Check out that sick color scheme. It's so appealing to the eyes.

**Comment by chrisvfritz** [comment]
Ha, very appealing color scheme. 😛  The use of the semantic elements looks great. 🎉  The only issues I see are in the structure and indentation of some of the HTML. Fortunately, [htmlhint](https://msu.lansing.codes/courses/MI-449-SS17-740/lessons/html-boilerplate-linting-and-code-style/2) will catch the instances of missing closing elements. Then once that's taken care of, you can actually get Atom to auto-indent the file for you by:

1. Selecting all text in the file
2. From Atom's top menu, clicking `Edit`->`Lines`->`Auto Indent`

Let me know if you have any questions! 🙂

**Comment by lordcrekit** [comment]
I should have been more rigorous in checking- my B. I totally thought I ran the G=gg (vim)! My bad again.

Should be good now.

**Comment by chrisvfritz** [comment]
Looks great! 🙂 🎉 :shipit:
